language: objective-c
before_install:
  - rvm: 1.9.3
  - export LANG=en_US.UTF-8
  - brew update
  - brew upgrade xctool
  - gem install cocoapods -v '0.37.1'
script:
  - xctool -workspace IBM.xcworkspace -scheme IBM -sdk iphonesimulator clean build test
