language: objective-c
before_install:
  - sudo easy_install cpp-coveralls
  - export LANG=en_US.UTF-8
  - brew update
  - brew upgrade xctool
  - gem install cocoapods -v '0.37.1'
script:
  - xctool -workspace IBM.xcworkspace -scheme IBM -sdk iphonesimulator clean build test ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - ./script/coveralls.sh
